export const list_types = [
  { id: 1, name: "Đồ ăn vặt" },
  { id: 2, name: "Chè" },
  { id: 3, name: "Nước uống" },
  { id: 4, name: "Rượu" },
  { id: 5, name: "Coffee" },
];
export const list_products = [
  {
    id: 1,
    name: "Bánh tráng trộn",
    price: 10000,
    src: require("./assets/images/banhtrang.jpg"),
    type: 1,
  },
  {
    id: 2,
    name: "Bún bò",
    price: 15000,
    src: require("./assets/images/bunbo.jpg"),
    type: 1,
  },
  {
    id: 3,
    name: "Bún thịt nướng",
    price: 15000,
    src: require("./assets/images/bunnuong.jpg"),
    type: 1,
  },
  {
    id: 4,
    name: "Chè đậu xanh",
    price: 15000,
    src: require("./assets/images/chedauxanh.jpg"),
    type: 2,
  },
  {
    id: 5,
    name: "Chè khúc bạch",
    price: 15000,
    src: require("./assets/images/chekhucbach.jpg"),
    type: 2,
  },
  {
    id: 6,
    name: "Chè Thái",
    price: 15000,
    src: require("./assets/images/chethai.jpg"),
    type: 2,
  },
  {
    id: 7,
    name: "Chè thập cẩm",
    price: 15000,
    src: require("./assets/images/chethapcam.jpg"),
    type: 2,
  },
  {
    id: 8,
    name: "Cơm chiên Dương Châu",
    price: 15000,
    src: require("./assets/images/comchien.jpg"),
    type: 1,
  },
  {
    id: 9,
    name: "Mì Samyang",
    price: 15000,
    src: require("./assets/images/misamyang.jpg"),
    type: 1,
  },
  {
    id: 10,
    name: "Nước ép cam",
    price: 15000,
    src: require("./assets/images/nuoccam.jpg"),
    type: 3,
  },
  {
    id: 11,
    name: "Nước ép dâu",
    price: 15000,
    src: require("./assets/images/nuocdau.jpg"),
    type: 3,
  },
  {
    id: 12,
    name: "Nước ép dứa",
    price: 15000,
    src: require("./assets/images/nuocdua.jpg"),
    type: 3,
  },
  {
    id: 13,
    name: "Nước ép táo",
    price: 15000,
    src: require("./assets/images/nuoctao.jpg"),
    type: 3,
  },
];
